name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: bash build.sh
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: rclonefunction.zip
          token: ${{secrets.GITHUB_TOKEN}}
